version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'go-poc'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 1s
      timeout: 1s
      retries: 55