// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"
)

type Asset struct {
	ID          string    `json:"ID"`
	Owner       string    `json:"Owner"`
	Name        string    `json:"Name"`
	Description string    `json:"Description"`
	URI         string    `json:"URI"`
	CreatedAt   time.Time `json:"CreatedAt"`
	UpdatedAt   time.Time `json:"UpdatedAt"`
}

type Me struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Mutation struct {
}

type NewAsset struct {
	Name        string `json:"Name"`
	Description string `json:"Description"`
	URI         string `json:"URI"`
}

type Query struct {
}
