package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"
)

// CreateAsset is the resolver for the createAsset field.
func (r *mutationResolver) CreateAsset(ctx context.Context, input NewAsset) (NewAssetResponse, error) {
	panic(fmt.Errorf("not implemented: CreateAsset - createAsset"))
}

// UpdateAsset is the resolver for the updateAsset field.
func (r *mutationResolver) UpdateAsset(ctx context.Context, input UpdateAsset) (Asset, error) {
	panic(fmt.Errorf("not implemented: UpdateAsset - updateAsset"))
}

// DeleteAsset is the resolver for the deleteAsset field.
func (r *mutationResolver) DeleteAsset(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAsset - deleteAsset"))
}

// UploadAsset is the resolver for the uploadAsset field.
func (r *mutationResolver) UploadAsset(ctx context.Context, id string) (PresignedURL, error) {
	panic(fmt.Errorf("not implemented: UploadAsset - uploadAsset"))
}

// Assets is the resolver for the assets field.
func (r *queryResolver) Assets(ctx context.Context, pagination *Pagination) ([]Asset, error) {
	panic(fmt.Errorf("not implemented: Assets - assets"))
}

// Asset is the resolver for the asset field.
func (r *queryResolver) Asset(ctx context.Context, id string) (*Asset, error) {
	panic(fmt.Errorf("not implemented: Asset - asset"))
}
