// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"
)

type Asset struct {
	ID          string    `json:"ID"`
	Name        string    `json:"Name"`
	Description string    `json:"Description"`
	URI         string    `json:"URI"`
	CreatedAt   time.Time `json:"CreatedAt"`
	UpdatedAt   time.Time `json:"UpdatedAt"`
}

type Header struct {
	Key   string `json:"Key"`
	Value string `json:"Value"`
}

type Me struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Mutation struct {
}

type NewAsset struct {
	Name        string `json:"Name"`
	Description string `json:"Description"`
}

type Pagination struct {
	Count int `json:"count"`
	Page  int `json:"page"`
}

type PresignedURL struct {
	URL    string   `json:"URL"`
	Fields []Header `json:"Fields"`
}

type Query struct {
}

type UpdateAsset struct {
	ID          string  `json:"ID"`
	Name        *string `json:"Name,omitempty"`
	Description *string `json:"Description,omitempty"`
}
