package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"

	"github.com/aws/smithy-go/ptr"
)

// Empty is the resolver for the empty field.
func (r *mutationResolver) Empty(ctx context.Context) (*bool, error) {
	return ptr.Bool(false), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (Me, error) {
	return Me{}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
